#!/bin/zsh
_dotfiles_git_ignore_add() {
  echo "Adding a few good ideas to $HOME/.gitignore file"
  ignore_list=(
    ".ssh"          
  )
  echo "'# Added by dotfiles-plus plugin on '$(date)" >> $HOME/.gitignore
  for i in ${ignore_list}; do
    echo "Adding $i"
    echo "$i\n" >> $HOME/.gitignore    
  done
  return $?
}

if [[ -f $HOME/.gitignore ]]; then
  echo "Existing .gitignore file found:"
  cat $HOME/.gitignore
  echo "Would you like to create a backup of your existing .gitignore file \nand add some sensibile sauce to it? (Y/n)"
  read -qs "ans?"
  if [[ $ans = y ]]; then    
    backup=$HOME/.gitignore.pre.dotfiles-plus
    \cp -fp $HOME/.gitignore $backup
    echo "$backup created"
    _dotfiles_git_ignore_add      
  else
    echo "Alright. I'll just ignore your .gitignore file then."
    return 0
  fi    
else
  echo "No .gitignore file found in $HOME.\nCreating .gitignore"
  _dotfiles_git_ignore_add
fi

